
services:
  api:
    build:
      context: .
      dockerfile: src/dockerfile
#    depends_on:
#      - db
#    volumes:
#      - .
    environment:
      - DB_USERNAME=fix
      - DB_PASSWORD=This
      - DATABASE_URL=postgresql://fix:This@dockerfun
      - ENV=development
      - LOGGER_LEVEL=DEBUG
    ports:
      - "8000:8000"

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fix
      - POSTGRES_PASSWORD=This
      - POSTGRES_DB=dockerfun
    ports:
      - "5432:5432"

volumes:
  postgres_data:
