FROM python:3.11
LABEL authors="Thiago.Weidman"

WORKDIR /src

COPY src/main.py requirements.txt /src/

ADD src/pricetag /src/pricetag

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
